[package]
name = "hylo-idl"
version.workspace = true
edition.workspace = true
description = "Protocol IDL definitions"
license.workspace = true
homepage.workspace = true
include = ["idls/", "src/"]

[features]
shadow = []

[[bin]]
name = "lut-accounts"
path = "src/bin/lut_accounts.rs"

[dependencies]
anchor-lang.workspace = true
anchor-spl.workspace = true
anyhow.workspace = true
const-crypto.workspace = true
hylo-fix.workspace = true
solana-address-lookup-table-interface.workspace = true

[lints]
workspace = true
