[package]
name = "hylo-core"
version.workspace = true
edition.workspace = true
description = "Core protocol data types, math, and utilities."
license.workspace = true
homepage.workspace = true

[features]
default = []
offchain = [
  "dep:hylo-idl",
  "hylo-fix/typed-floats",
]
shadow = ["hylo-idl?/shadow"]

[dependencies]
anchor-lang.workspace = true
anchor-spl.workspace = true
hylo-fix.workspace = true
const-crypto.workspace = true
hylo-idl = { workspace = true, optional = true }
itertools.workspace = true
pyth-solana-receiver-sdk.workspace = true
serde.workspace = true

[dev-dependencies]
anyhow.workspace = true
more-asserts.workspace = true
proptest.workspace = true

[lints]
workspace = true
